"""
inspect_panel.py
================
Map the structure of every downloaded ENAHO Panel .dta WITHOUT loading the data
matrix (some wide files are 6-8 GB). Uses pyreadstat metadata + targeted small
column reads only.

For each file it reports:
  * layout: WIDE (year-suffixed _NN columns, one row per panel household) or
            LONG (an explicit anio/aÃ±o column), classified from column names;
  * waves: the set of years, read from the _NN suffixes (wide) or by a tiny
           read of the year column (long);
  * longitudinal anchor key (conglome/vivienda/hogar or cong/vivi/num_hog);
  * any INEI balanced-window flags hpan<window> + longitudinal weights
    fac_panel<window> present, and the size of the longest balanced window
    (tiny usecols read of that one flag).

Output: docs/PANEL_STRUCTURE.md + datasets/panel_file_keys.csv
Run:  py -3.14 inspect_panel.py
"""
from __future__ import annotations

import csv
import re
from pathlib import Path

import pyreadstat

ROOT = Path(__file__).resolve().parents[1]
PANEL = ROOT / "raw" / "panel"
MANIFEST = PANEL / "_panel_manifest.csv"
DOCS = ROOT / "docs"
DATASETS = ROOT / "datasets"

SUFFIX_RE = re.compile(r"_(0[0-9]|1[0-9]|2[0-9])$")
ANCHOR_SETS = [["conglome", "vivienda", "hogar"], ["cong", "vivi", "num_hog"],
               ["cong", "vivi", "hog"]]
YEAR_COLS = ["anio", "aÃ±o", "ano", "year"]


def _anchor(low: set) -> list[str]:
    for s in ANCHOR_SETS:
        if all(c in low for c in s):
            return s
    return []


def classify(path: Path) -> dict:
    _, meta = pyreadstat.read_dta(str(path), metadataonly=True)
    cols = meta.column_names
    low = {c.lower() for c in cols}
    lower_map = {c.lower(): c for c in cols}

    suff_years = sorted({2000 + int(m.group(1))
                         for c in cols if (m := SUFFIX_RE.search(c.lower()))})
    year_col = next((c for c in YEAR_COLS if c in low), "")
    layout = "long" if year_col else ("wide" if len(suff_years) >= 2 else "flat")

    waves = list(suff_years)
    if layout == "long" and year_col:
        try:
            df, _ = pyreadstat.read_dta(str(path), usecols=[lower_map[year_col]])
            waves = sorted(int(v) for v in df[lower_map[year_col]].dropna().unique())
        except Exception:
            pass

    hpan = sorted({m.group(1) for c in cols if (m := re.match(r"hpan(\d{4})$", c.lower()))},
                  key=lambda w: int(w[2:]) - int(w[:2]), reverse=True)
    facpanel = [c for c in cols if c.lower().startswith("fac_panel")]
    anchor = _anchor(low)

    balanced_hh = ""
    if hpan:
        flag = next(c for c in cols if c.lower() == f"hpan{hpan[0]}")
        try:
            df, _ = pyreadstat.read_dta(str(path), usecols=[flag])
            balanced_hh = int((df[flag] == 1).sum())
        except Exception:
            pass

    return {
        "file": path.name, "layout": layout, "n_cols": len(cols),
        "n_rows_total": int(meta.number_rows or 0),
        "waves": ";".join(map(str, waves)),
        "anchor_key": "+".join(anchor),
        "has_codperso": "codperso" in low,
        "hpan_windows": ";".join(hpan),
        "longest_balanced_hh": balanced_hh,
        "fac_panel_vars": ";".join(facpanel[:6]),
    }


def main() -> None:
    if not MANIFEST.exists():
        print("no manifest yet")
        return
    rows = list(csv.DictReader(open(MANIFEST, encoding="utf-8")))
    results = []
    for r in rows:
        p = Path(r["path"])
        if not p.exists():
            continue
        print(f"classify {r['release']} M{r['module']} {p.name} ...", flush=True)
        try:
            results.append({"release": r["release"], "code": r["code"],
                            "module": r["module"], **classify(p)})
        except Exception as e:                              # noqa: BLE001
            print(f"  ! {e}")

    DATASETS.mkdir(exist_ok=True)
    cols = ["release", "code", "module", "file", "layout", "n_rows_total",
            "n_cols", "waves", "anchor_key", "has_codperso", "hpan_windows",
            "longest_balanced_hh", "fac_panel_vars"]
    out = DATASETS / "panel_file_keys.csv"
    with open(out, "w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=cols)
        w.writeheader()
        for r in results:
            w.writerow({c: r.get(c, "") for c in cols})
    print(f"\nwrote {out} ({len(results)} files)")

    DOCS.mkdir(exist_ok=True)
    with open(DOCS / "PANEL_STRUCTURE.md", "w", encoding="utf-8") as f:
        f.write("# ENAHO Panel - empirical file structure\n\n")
        f.write("Auto-generated by `inspect_panel.py` (metadata-only; no full loads).\n")
        f.write("One row per downloaded `.dta`.\n\n")
        f.write("| release | mod | file | layout | rows | cols | waves | anchor key | hpan window | balanced hh |\n")
        f.write("|--|--|--|--|--|--|--|--|--|--|\n")
        for r in sorted(results, key=lambda x: (x["release"], x["module"])):
            f.write(f"| {r['release']} | {r['module']} | {r['file']} | {r['layout']} "
                    f"| {r['n_rows_total']:,} | {r['n_cols']} | {r['waves']} "
                    f"| {r['anchor_key']} | {r['hpan_windows']} | {r['longest_balanced_hh']} |\n")
    print(f"wrote {DOCS / 'PANEL_STRUCTURE.md'}")


if __name__ == "__main__":
    main()
